package com.xcaret.xcaret_hotel.view.config

enum class FragmentTags(val value: String) {
    Splash("SplashFragment"),
    Home("HomeFragment"),
    Map("MapFragment"),
    AFI("AFIFragment"),
    Menu("MenuFragment"),
    Profile("ProfileFragment"),
    Login("LoginFragment"),
    ForgotPassword("ForgotPasswordFragment"),
    SignUp("SignUpFragment"),
    RoomList("RoomListFragment"),
    RoomDetail("RoomDetailFragment"),
    RestaurantList("RestaurantListFragment"),
    RestaurantDetail("RestaurantDetailFragment"),
    PoolDetailFragment("PoolDetailFragment"),
    BuldingDetail("BuildingDetailFragment"),
    ParkDetail("ParkDetailFragment"),
    FerryDetail("FerryDetailFragment"),
    Weather("WeatherFragment"),
    AboutHotel("AboutHotelFragment"),
    YoutubePlayer("YoutubePlayerActivity"),
    QuoteFragment("QuoteFragment"),
    MyReservations("MyReservationFragment"),
    BuyerDataFragment("BuyerDataFragment"),
    PaymentFragment("PaymentFragment"),
    PickupFragment("PickupFragment"),
    WorkShopList("WorkShopList"),
    WorkShopDetail("WorkShopDetail"),
    Faq("FAQsFragment"),
    FaqsDetail("FAQsDetailFragment"),
    EventList("EventListFragment"),
    EventDetail("EventDetailFragment")
}